name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        if: github.event.action != 'closed'
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.145.0'
          extended: true

      - name: Build (production)
        if: github.event_name == 'push'
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --gc \
            --minify \
            --destination ./docs

      - name: Build (PR preview)
        if: github.event_name == 'pull_request' && github.event.action != 'closed'
        env:
          HUGO_ENVIRONMENT: development
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "https://chechia.net/pr-preview/pr-${{ github.event.number }}/" \
            --destination ./docs

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          cname: chechia.net

      - name: Deploy PR Preview
        if: github.event_name == 'pull_request' && github.event.action != 'closed'
        uses: rosario/deploy-pr-preview@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deploy-dir: docs

      - name: Remove PR Preview
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        uses: rosario/deploy-pr-preview@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          action: remove
